name: CI/CD
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
jobs:
  # Testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Check directory Files
  #       run: ls
  #     - name: Check docker version
  #       run: docker --version
  #     - name: Docker login
  #       run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #     - name: Build test docker image
  #       run: docker build -t drakemage47/react-test -f ./client/Dockerfile.dev ./client
  #     - name: Run client test
  #       run: docker run -e CI=true drakemage47/react-test npm test
  
  Deploy:
    # needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name:
        run: node --version
      - name: Checkout code
        uses: actions/checkout@v4
      - name: GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}}
      - name: Configure GCP
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components install kubectl
          gcloud components install gke-gcloud-auth-plugin
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/zone us-west1-a
          gcloud container clusters get-credentials multi-cluster
      - name: Docker login 
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: testing kubectl
        run: |
          kubectl get pods
