name: CI/CD
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actoins/checkout@v4
      - name: Check directory Files
        run: ls
      - name: Check docker version
        run: docker --version
      - name: Docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build test docker image
        run: docker build -t drakemage47/react-test -f ./client/Dockerfile.dev ./client
      - name: Run client test
        run: docker run -e CI=true drakemage47/react-test npm test
  
  # deploy:
  #   needs: Testing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install google cloud SDK
  #       run: |
  #         curl https://sdk.cloud.google.com | bash > /dev/null;
  #         source $HOME/google-cloud-sdk/path.bash.inc
  #         gcloud components update kubectl
