name: CI/CD
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
jobs:
  # Testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Check directory Files
  #       run: ls
  #     - name: Check docker version
  #       run: docker --version
  #     - name: Docker login
  #       run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #     - name: Build test docker image
  #       run: docker build -t drakemage47/react-test -f ./client/Dockerfile.dev ./client
  #     - name: Run client test
  #       run: docker run -e CI=true drakemage47/react-test npm test
  
  Deploy:
    # needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name:
        run: node --version
      - name: Checkout code
        uses: actions/checkout@v4
      - name: GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Check configuration versions
        run: |
          kubectl version --client
          gke-gcloud-auth-plugin --version
      - name: Docker login 
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: testing kubectl
        run: |
          kubectl get namespaces
