name: CI/CD
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actoins/checkout@v4
      - name: Check directory Files
        run: ls
      - name: Check docker version
        run: docker --version
      - name: Build test docker image
        run: docker build -t drakemage47/react-test -f ./client/Dockerfile.dev ./client
      - name: Run client test
        run: docker run -e CI=true drakemage47/react-test npm test
    
