name: test-deploy-action
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actoins/checkout@v4
      - name: test
        run: ls
    
